name: CI Flask API

on:
  push:
    branches: [ main ]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
      - name: Save venv
        uses: actions/upload-artifact@v3
        with:
          name: venv
          path: venv

  test:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Download venv
        uses: actions/download-artifact@v3
        with:
          name: venv
          path: venv
      - name: Run unit tests
        run: |
          source venv/bin/activate
          pytest

  coverage:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Download venv
        uses: actions/download-artifact@v3
        with:
          name: venv
          path: venv
      - name: Run coverage report
        run: |
          source venv/bin/activate
          pytest --cov=app --cov=models --cov-report=term-missing
